import { DEFAULT_PARAMS, type SimParams } from './config';

export interface Preset {
  name: string;
  params: SimParams;
  note?: string;
}

const STORAGE_KEY = 'daosim.presets';

/**
 * Three living presets chosen from the top of the milestone-1 sweep
 * (public/sweep-results.json, generated by `npm run sweep`) — all cleared
 * the acceptance bar (sustained motion, mid-range spatial structure, no
 * monoculture) and were picked for variety across the alpha/beta/mu that
 * scored equally well. Regenerate/audition more via Gallery mode (key: G).
 */
export const BUILTIN_PRESETS: Preset[] = [
  {
    name: 'Even Weave',
    params: { ...DEFAULT_PARAMS, alpha: 0.8, beta: 0.7, mu: 0.15, size: 128 },
    note: 'Baseline living region: gentle generation lead over suppression, moderate diffusion.',
  },
  {
    name: 'Quick Bloom',
    params: { ...DEFAULT_PARAMS, alpha: 1.0, beta: 0.7, mu: 0.15, size: 128 },
    note: 'Faster generation relative to suppression — tighter, quicker-turning domains.',
  },
  {
    name: 'Wide Diffuse',
    params: { ...DEFAULT_PARAMS, alpha: 1.2, beta: 1.1, mu: 0.25, size: 128 },
    note: 'Stronger generation and suppression both scaled up, with heavier diffusion smoothing the fronts.',
  },
];

export function loadUserPresets(): Preset[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? (JSON.parse(raw) as Preset[]) : [];
  } catch {
    return [];
  }
}

export function saveUserPreset(preset: Preset): void {
  const presets = loadUserPresets();
  presets.push(preset);
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(presets));
  } catch {
    // storage unavailable (e.g. artifact sandbox) — preset just won't persist across reloads
  }
}

export function allPresets(): Preset[] {
  return [...BUILTIN_PRESETS, ...loadUserPresets()];
}
